# This file is part of the django-environ.
#
# Copyright (c) 2021, Serghei Iakovlev <egrep@protonmail.ch>
# Copyright (c) 2013-2021, Daniele Faraglia <daniele.faraglia@gmail.com>
#
# For the full copyright and license information, please view
# the LICENSE.txt file that was distributed with this source code.

---
version: 2
python:
  # Keep version in sync with tox.ini (testenv:docs) and
  # docs.yml (GitHub Action Workflow).
  version: '3.8'

  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
