# https://ci.appveyor.com/project/joke2k/django-environ
build: false
environment:
  PYTHONIOENCODING: "utf-8"
  matrix:
    - PYTHON: "C:/Python27"
      DJANGO_VERSION: "Django>=1.8,<1.9"

    - PYTHON: "C:/Python27"
      DJANGO_VERSION: "Django>=1.9,<1.10"

    - PYTHON: "C:/Python27"
      DJANGO_VERSION: "Django>=1.10,<1.11"

    - PYTHON: "C:/Python27"
      DJANGO_VERSION: "Django>=1.11,<2.0"

    - PYTHON: "C:/Python35"
      DJANGO_VERSION: "Django>=1.8,<1.9"

    - PYTHON: "C:/Python35"
      DJANGO_VERSION: "Django>=1.9,<1.10"

    - PYTHON: "C:/Python35"
      DJANGO_VERSION: "Django>=1.10,<1.11"

    - PYTHON: "C:/Python35"
      DJANGO_VERSION: "Django>=1.11,<2.0"

    - PYTHON: "C:/Python35"
      DJANGO_VERSION: "Django>=2.0,<2.1"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
install:
  - ps: |
      [Net.ServicePointManager]::SecurityProtocol = 'Tls11, Tls12'
      (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install \"%DJANGO_VERSION%\""
  - "%PYTHON%/Scripts/pip.exe install -e ."
test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/python.exe setup.py test"
